### PR TITLE
refactor(logistics/ui): fix some ui issues and logistics bug

### PR DESCRIPTION
**Pull request by luxferoo**

### CODE REVIEW

**Comment by luxferoo** [comment]
Hi @mardtendebakker ! Is this size enough ? 

Capture

**Comment by mardtendebakker** [comment]
hi @luxferoo 
according to input of the drivers, half the screen or 2/3 of the screen would be great.

**Comment by luxferoo** [comment]
@mardtendebakker height of the map or the sidenav ? yes I can make the map display full in height and half the screen, then if they scroll down they see details, is that what's wanted?

**Comment by mardtendebakker** [comment]
something like this if possible makes more sense . the map is big and to the right you can have the sidenav

logistics-popup

**Comment by luxferoo** [comment]
done ! @shayank I also fixed the bug you shared with me earlier about opening a pickup without logistic

**Comment by shayank** [comment]
super! thanks! @luxferoo

**Pull request merged**
